language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database testing_db;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - yarn
script:
  - vendor/bin/phpunit
after_success:
  - bash <(curl -s https://codecov.io/bash)
